[technote]
id = "SITCOMTN-094"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-094.lsst.io/"
github_url = "https://github.com/lsst-sitcom/sitcomtn-094"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
